/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ps.views;

import com.ps.controllers.ImpressoController;
import com.ps.models.datas.ImpressoData;
import com.ps.models.services.LoginService;
import com.ps.models.datas.RetiradaData;
import java.awt.List;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import static sun.security.jgss.GSSUtil.login;

/**
 *
 * @author elrafa
 */
public class InterfaceRetirada extends javax.swing.JFrame {
    ArrayList<String[]> lista = new ArrayList<>();
    String[] nomesColunas = {"Nome do Impresso", "Autor", "Quantidade"};
    Boolean isOrNot = false;
    int matricula;
    /**
     * Creates new form InterfacePesquisa
     */
    public InterfaceRetirada() {
        initComponents();
        InitTable();
        setLocationRelativeTo(null);
    }
    
    public InterfaceRetirada(int matricula) {
        this.matricula = matricula;
        initComponents();
        InitTable();
        setLocationRelativeTo(null);
    }
    
    public void InitTable(){
        DefaultTableModel model = new DefaultTableModel(
        lista.toArray(new String[lista.size()][]), nomesColunas);
        jTable1.setModel(model);
    
    
        //String[] nomesColunas = {"Nome do Impresso", "Autor", "Quantidade"};
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        textFieldIdRetiradaDevolver = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        devolverButton = new javax.swing.JButton();
        textFieldIdExemplarDevolver = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        messageSearch = new javax.swing.JLabel();
        voltarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        searchButton.setText("Pesquisar Empréstimos");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        textFieldIdRetiradaDevolver.setEditable(false);

        jLabel2.setText("ID da Retirada");

        jLabel3.setText("DEVOLUÇÃO");

        devolverButton.setText("Devolver Livro");
        devolverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                devolverButtonActionPerformed(evt);
            }
        });

        textFieldIdExemplarDevolver.setEditable(false);

        jLabel4.setText("ID do Exemplar");

        messageSearch.setText("Selecione o empréstimo que deseja devolver");
        messageSearch.setEnabled(false);

        voltarButton.setText("Voltar");
        voltarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(messageSearch)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 734, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(316, 316, 316)
                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 51, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(voltarButton)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(377, 377, 377)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldIdRetiradaDevolver, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldIdExemplarDevolver, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(37, 37, 37)
                        .addComponent(devolverButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(voltarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(messageSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldIdRetiradaDevolver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldIdExemplarDevolver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(devolverButton)))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("empty-statement")
    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        pesquisar();

    }//GEN-LAST:event_searchButtonActionPerformed
    
    public void pesquisar(){
        lista.removeAll(lista);
    messageSearch.setEnabled(true);
    
    ImpressoController ic = new ImpressoController();
    ResultSet resultado = ic.buscaImpressoDevolver(this.matricula);
    
    String[] nomesColunas = {"IdRetirada", "IdExemplar", "DataRetirada"};
    int i=0;
        try {
            while(resultado.next()){
                lista.add(new String[]{
                    resultado.getString("idRetirada"),
                    resultado.getString("idExemplar"),
                    resultado.getString("DataRetirada")});
                i++;
            }
       
            DefaultTableModel model = new DefaultTableModel(
            lista.toArray(new String[lista.size()][]), nomesColunas) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };
            
            jTable1.setModel(model);
            
            //initTable();
            //essa lista terá as linhas da sua JTable, preenchi abaixo apenas como exemplo
            //aqui você fará um while percorrendo seu result set e adicionando na lista
            //while(resultset.next()) {
            /*
            lista.add(new String[]{"O Príncipe", "MAQUIAVEL, N.", "3"});
            lista.add(new String[]{"O Existencialismo é um Humanismo", "SARTRE, J. P.", "4"});
            lista.add(new String[]{"Assim falava Zaratustra", "NIETZSCHE, F.", "1"});
            if(isOrNot) lista.add(new String[]{"Fortaleza Digital", "BROWN, D.", "1"});
            DefaultTableModel model = new DefaultTableModel(
            lista.toArray(new String[lista.size()][]), nomesColunas);
            jTable1.setModel(model);
            
            isOrNot = true;
            */
            
            //for(int i=0; i < 20; i++) jTable1.add(new Object[]("NUMERO" + i,""+i, "TESTANDO" + i));
        } catch (SQLException ex) {
            Logger.getLogger(InterfacePesquisa.class.getName()).log(Level.SEVERE, null, ex);
        }
 
    }
    
    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        if(evt.getClickCount() == 2) {
            String value = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
            String value2 = jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString();
            textFieldIdRetiradaDevolver.setText(value);
            textFieldIdExemplarDevolver.setText(value2);
        }
    }//GEN-LAST:event_jTable1MousePressed

    private void devolverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_devolverButtonActionPerformed
    if(!textFieldIdRetiradaDevolver.getText().equals("")){
        ImpressoData retiradaData = new ImpressoData();
        if(retiradaData.devolveExemplar(
                Integer.parseInt(textFieldIdRetiradaDevolver.getText()),
                Integer.parseInt(textFieldIdExemplarDevolver.getText())))
            JOptionPane.showMessageDialog(rootPane, "LIVRO DEVOLVIDO COM SUCESSO");
        else JOptionPane.showMessageDialog(rootPane, "OCORREU UM ERRO AO DEVOLVER O LIVRO");
    }
    textFieldIdRetiradaDevolver.setText("");
    textFieldIdExemplarDevolver.setText("");
    pesquisar();
    
    }//GEN-LAST:event_devolverButtonActionPerformed

    private void voltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButtonActionPerformed
        this.dispose();
        InterfacePesquisa ipesquisa = new InterfacePesquisa(matricula);
        ipesquisa.show();
    }//GEN-LAST:event_voltarButtonActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfacePesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfacePesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfacePesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfacePesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfacePesquisa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton devolverButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel messageSearch;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField textFieldIdExemplarDevolver;
    private javax.swing.JTextField textFieldIdRetiradaDevolver;
    private javax.swing.JButton voltarButton;
    // End of variables declaration//GEN-END:variables
}
